BEARER_TOKEN: "AAAAAAAAAAAAAAAAAAAAAECVlQEAAAAApawcFUPZhhOitAIVWIGSEK3ZygU%3D5ZWGrIYJpRRJ2j3R9TKIm9tMNuYgce1KAZ6NTau6dixLeLvcYD"
CONSUMER_KEY: "VbM10xyc5wAKiooe8fbfXRV8L"
CONSUMER_SECRET: "2rFcjzcFEgTAlMLRb3VUyfjR8bayLOayRn28p4b4FpTDY11gA4"
ACCESS_TOKEN: "3277696218-j307oxsqeulv7qdbX1Fc1pfDgVeE3QV5pdzLRGu"
ACCESS_TOKEN_SECRET: "lBw374TvEigwsSnKSmMAnvBLQjqtJ9QaqWu0V1nOfQ61s"
